FROM dockerregistry.lnls-sirius.com.br/lnlsdig/basler-aca1300-75gm-epics-ioc:3.2.0-base-3.15-debian-9
RUN apt update -y && apt install -y socat procps vim
COPY runProcServ.sh /opt/epics/startup/ioc/basler-acA1300-75gm-epics-ioc/iocBoot/iocBasleracA130075gm/runProcServ.sh
RUN ls -la && pwd
