version: "3.8"
services:

  ioc:
    image: dockerregistry.lnls-sirius.com.br/gas/basler-aca1300-75gm-epics-ioc:${IOC_COMMIT}-base-3.15-debian-9
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        org.opencontainers.image.revision: ${IOC_COMMIT}
        org.opencontainers.image.source: https://github.com/${IOC_GROUP}/${IOC_REPO}.git
      args:
        IOC_GROUP: ${IOC_GROUP}
        IOC_REPO: ${IOC_REPO}
        IOC_COMMIT: ${IOC_COMMIT}

  fallback:
    image: dockerregistry.lnls-sirius.com.br/gas/basler-aca1300-75gm-epics-ioc:3.2.0-socat-rc1-base-3.15-debian-9
    build:
      context: .
      dockerfile: Dockerfile.fallback
